var generalQuestions=[{question:"India ki rajdhani kya hai?",options:["Mumbai","New Delhi","Kolkata","Chennai"],correct:1},{question:"India mein kitne states hain?",options:["25","26","28","29"],correct:2},{question:"India ka rashtriya khel?",options:["Cricket","Hockey","Football","Kabaddi"],correct:1},{question:"Taj Mahal kahan hai?",options:["Delhi","Jaipur","Agra","Lucknow"],correct:2},{question:"India ka sabse bada state?",options:["UP","MP","Rajasthan","Maharashtra"],correct:2},{question:"India ki currency?",options:["Dollar","Rupee","Pound","Euro"],correct:1},{question:"India ka national animal?",options:["Lion","Elephant","Tiger","Peacock"],correct:2},{question:"India ka national bird?",options:["Sparrow","Parrot","Peacock","Eagle"],correct:2},{question:"India ka national fruit?",options:["Banana","Mango","Apple","Orange"],correct:1},{question:"India ka sabse lamba nadi?",options:["Yamuna","Ganga","Godavari","Krishna"],correct:1}];

var scienceQuestions=[{question:"Paani ka formula?",options:["CO2","H2O","O2","NaCl"],correct:1},{question:"Suraj se nazdeek planet?",options:["Venus","Earth","Mercury","Mars"],correct:2},{question:"Insaan ki haddiyan?",options:["196","206","216","226"],correct:1},{question:"Light ki speed?",options:["3 lakh km/s","2 lakh km/s","4 lakh km/s","5 lakh km/s"],correct:0},{question:"DNA full form?",options:["Deoxyribonucleic Acid","Deoxy Nucleic Acid","Double Nucleic Acid","Dynamic Acid"],correct:0},{question:"Sabse chhota planet?",options:["Mercury","Mars","Venus","Pluto"],correct:0},{question:"Oxygen atomic number?",options:["6","7","8","9"],correct:2},{question:"Khoon lal kyun?",options:["Hemoglobin","Iron","Oxygen","Protein"],correct:0},{question:"Gravity discovery?",options:["Newton","Einstein","Galileo","Darwin"],correct:0},{question:"Sabse bada planet?",options:["Jupiter","Saturn","Uranus","Neptune"],correct:0}];

var mathQuestions=[{question:"26+26=?",options:["52","56","67","57"],correct:0},{question:"89+104=?",options:["193","123","111","192"],correct:0},{question:"25% of 200=?",options:["50","40","60","70"],correct:0},{question:"2x2x2=?",options:["8","4","6","10"],correct:0},{question:"1+1x0=?",options:["1","0","2","3"],correct:0},{question:"100/4x2=?",options:["50","12","25","200"],correct:0},{question:"Triangle angles sum=?",options:["180","90","270","360"],correct:0},{question:"0.5x0.5=?",options:["0.25","0.10","0.50","1.00"],correct:0},{question:"12x12=?",options:["144","124","134","154"],correct:0},{question:"1000-357=?",options:["643","633","653","663"],correct:0}];

var customQuestions=[{question:"Best quiz app?",options:["AB-PROF","Kahoot","Quizizz","Other"],correct:0},{question:"Mobile se app banana?",options:["Possible hai","Nahi","Shayad","Pata nahi"],correct:0},{question:"Firebase kya hai?",options:["Database","Game","App","Browser"],correct:0},{question:"HTML full form?",options:["HyperText Markup Language","High Text ML","Home Tool ML","None"],correct:0},{question:"CSS kaam kya?",options:["Styling","Database","Logic","Server"],correct:0},{question:"JS full form?",options:["JavaScript","Java System","Just Script","Java Server"],correct:0},{question:"Netlify kya hai?",options:["Hosting","Database","Editor","Browser"],correct:0},{question:"AB-PROF banaya kisne?",options:["Maine","Google","Apple","Microsoft"],correct:0},{question:"Quiz mein timer?",options:["30 sec","60 sec","15 sec","45 sec"],correct:0},{question:"Leaderboard kya dikhata?",options:["Rankings","Weather","News","Music"],correct:0}];

window.generalQuestions=generalQuestions;
window.scienceQuestions=scienceQuestions;
window.mathQuestions=mathQuestions;
window.customQuestions=customQuestions;